spring:
  application: 
        name: terra
  data: 
    elasticsearch:
      cluster-name: my-es-dogs
      cluster-nodes: 192.168.0.213:9300,192.168.0.223:9300,192.168.0.220:9300
  kafka:
    consumer:
      bootstrap-servers: 202.153.207.179:8092,202.153.207.181:8092,202.153.207.182:8092
      enable-auto-commit: true
      auto-commit-interval: 100ms
      auto-offset-reset: latest
      group-id: terra_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      bootstrap-servers: 202.153.207.179:8092,202.153.207.181:8092,202.153.207.182:8092
      acks: 1
    listener:
      poll-timeout: 15s

server:
  port: 8095
logging:
  config: classpath:logback-spring.xml


eureka: 
    client:
        service-url:
           defaultZone: http://admin:${jhipster.registry.password}@192.168.0.217:8761/eureka/
        enabled: true
        healthcheck:
            enabled: false
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: terra
        instanceId: terra:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
        
ribbon:
    eureka:
        enabled: true


management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true