spring:
  application: 
        name: terra
  data: 
    elasticsearch:
      cluster-name: my-es-dogs
      cluster-nodes: 192.168.0.213:9300,192.168.0.223:9300,192.168.0.220:9300
      
server:
  port: 8095
logging:
  config: classpath:logback-spring.xml


eureka: 
    client:
        service-url:
           defaultZone: http://admin:${jhipster.registry.password}@192.168.0.217:8761/eureka/
        enabled: true
        healthcheck:
            enabled: false
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: terra
        instanceId: terra:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version}
        
ribbon:
    eureka:
        enabled: true


management:
    security:
        roles: ADMIN
    context-path: /management
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true